" Add line number
:set number

" Install plugins
call plug#begin('~/.vim/bundle/')

" Syntax-checker
Plug 'vim-syntastic/syntastic'

" Finish installation
call plug#end()

" configure syntax-checker
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

set signcolumn=yes

let g:syntastic_enable_signs = 1
let g:syntastic_enable_balloons = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:sysntastic_check_on_wq = 0
let g:syntastic_loc_list_height = 10

let g:syntastic_warning_symbol = "W>"

highlight SyntasticErrorLine guifg=white guibg=red
